//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("EServeurDatabaseModel", "FK_TblProduto_TblCategoria", "TblCategoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Eserveur.TblCategoria), "TblProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eserveur.TblProduto), true)]
[assembly: EdmRelationshipAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Eserveur.TblIngrediente), "TblProdutoIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eserveur.TblProdutoIngrediente), true)]
[assembly: EdmRelationshipAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblPedido", "TblPedido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Eserveur.TblPedido), "TblPedidoItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eserveur.TblPedidoItem), true)]
[assembly: EdmRelationshipAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblProduto", "TblProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Eserveur.TblProduto), "TblPedidoItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eserveur.TblPedidoItem), true)]
[assembly: EdmRelationshipAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblProduto", "TblProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Eserveur.TblProduto), "TblProdutoIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eserveur.TblProdutoIngrediente), true)]

#endregion

namespace Eserveur
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class EServeurDatabaseEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet EServeurDatabaseEntities à l'aide de la chaîne de connexion trouvée dans la section 'EServeurDatabaseEntities' du fichier de configuration d'application.
        /// </summary>
        public EServeurDatabaseEntities() : base("name=EServeurDatabaseEntities", "EServeurDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet EServeurDatabaseEntities.
        /// </summary>
        public EServeurDatabaseEntities(string connectionString) : base(connectionString, "EServeurDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet EServeurDatabaseEntities.
        /// </summary>
        public EServeurDatabaseEntities(EntityConnection connection) : base(connection, "EServeurDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblCategoria> TblCategoria
        {
            get
            {
                if ((_TblCategoria == null))
                {
                    _TblCategoria = base.CreateObjectSet<TblCategoria>("TblCategoria");
                }
                return _TblCategoria;
            }
        }
        private ObjectSet<TblCategoria> _TblCategoria;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblIngrediente> TblIngrediente
        {
            get
            {
                if ((_TblIngrediente == null))
                {
                    _TblIngrediente = base.CreateObjectSet<TblIngrediente>("TblIngrediente");
                }
                return _TblIngrediente;
            }
        }
        private ObjectSet<TblIngrediente> _TblIngrediente;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblPedido> TblPedido
        {
            get
            {
                if ((_TblPedido == null))
                {
                    _TblPedido = base.CreateObjectSet<TblPedido>("TblPedido");
                }
                return _TblPedido;
            }
        }
        private ObjectSet<TblPedido> _TblPedido;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblPedidoItem> TblPedidoItem
        {
            get
            {
                if ((_TblPedidoItem == null))
                {
                    _TblPedidoItem = base.CreateObjectSet<TblPedidoItem>("TblPedidoItem");
                }
                return _TblPedidoItem;
            }
        }
        private ObjectSet<TblPedidoItem> _TblPedidoItem;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblProduto> TblProduto
        {
            get
            {
                if ((_TblProduto == null))
                {
                    _TblProduto = base.CreateObjectSet<TblProduto>("TblProduto");
                }
                return _TblProduto;
            }
        }
        private ObjectSet<TblProduto> _TblProduto;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TblProdutoIngrediente> TblProdutoIngrediente
        {
            get
            {
                if ((_TblProdutoIngrediente == null))
                {
                    _TblProdutoIngrediente = base.CreateObjectSet<TblProdutoIngrediente>("TblProdutoIngrediente");
                }
                return _TblProdutoIngrediente;
            }
        }
        private ObjectSet<TblProdutoIngrediente> _TblProdutoIngrediente;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblCategoria. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblCategoria(TblCategoria tblCategoria)
        {
            base.AddObject("TblCategoria", tblCategoria);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblIngrediente. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblIngrediente(TblIngrediente tblIngrediente)
        {
            base.AddObject("TblIngrediente", tblIngrediente);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblPedido. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblPedido(TblPedido tblPedido)
        {
            base.AddObject("TblPedido", tblPedido);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblPedidoItem. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblPedidoItem(TblPedidoItem tblPedidoItem)
        {
            base.AddObject("TblPedidoItem", tblPedidoItem);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblProduto. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblProduto(TblProduto tblProduto)
        {
            base.AddObject("TblProduto", tblProduto);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TblProdutoIngrediente. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTblProdutoIngrediente(TblProdutoIngrediente tblProdutoIngrediente)
        {
            base.AddObject("TblProdutoIngrediente", tblProdutoIngrediente);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblCategoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblCategoria : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblCategoria.
        /// </summary>
        /// <param name="categoria_id">Valeur initiale de la propriété Categoria_id.</param>
        /// <param name="nome">Valeur initiale de la propriété Nome.</param>
        public static TblCategoria CreateTblCategoria(global::System.Int32 categoria_id, global::System.String nome)
        {
            TblCategoria tblCategoria = new TblCategoria();
            tblCategoria.Categoria_id = categoria_id;
            tblCategoria.Nome = nome;
            return tblCategoria;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoria_id
        {
            get
            {
                return _Categoria_id;
            }
            set
            {
                if (_Categoria_id != value)
                {
                    OnCategoria_idChanging(value);
                    ReportPropertyChanging("Categoria_id");
                    _Categoria_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Categoria_id");
                    OnCategoria_idChanged();
                }
            }
        }
        private global::System.Int32 _Categoria_id;
        partial void OnCategoria_idChanging(global::System.Int32 value);
        partial void OnCategoria_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProduto_TblCategoria", "TblProduto")]
        public EntityCollection<TblProduto> TblProduto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblProduto>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblProduto>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblProduto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblIngrediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblIngrediente : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblIngrediente.
        /// </summary>
        /// <param name="ingrediente_id">Valeur initiale de la propriété Ingrediente_id.</param>
        /// <param name="nome">Valeur initiale de la propriété Nome.</param>
        /// <param name="esta_disponivel">Valeur initiale de la propriété Esta_disponivel.</param>
        public static TblIngrediente CreateTblIngrediente(global::System.Int32 ingrediente_id, global::System.String nome, global::System.Boolean esta_disponivel)
        {
            TblIngrediente tblIngrediente = new TblIngrediente();
            tblIngrediente.Ingrediente_id = ingrediente_id;
            tblIngrediente.Nome = nome;
            tblIngrediente.Esta_disponivel = esta_disponivel;
            return tblIngrediente;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ingrediente_id
        {
            get
            {
                return _Ingrediente_id;
            }
            set
            {
                if (_Ingrediente_id != value)
                {
                    OnIngrediente_idChanging(value);
                    ReportPropertyChanging("Ingrediente_id");
                    _Ingrediente_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ingrediente_id");
                    OnIngrediente_idChanged();
                }
            }
        }
        private global::System.Int32 _Ingrediente_id;
        partial void OnIngrediente_idChanging(global::System.Int32 value);
        partial void OnIngrediente_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Esta_disponivel
        {
            get
            {
                return _Esta_disponivel;
            }
            set
            {
                OnEsta_disponivelChanging(value);
                ReportPropertyChanging("Esta_disponivel");
                _Esta_disponivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Esta_disponivel");
                OnEsta_disponivelChanged();
            }
        }
        private global::System.Boolean _Esta_disponivel;
        partial void OnEsta_disponivelChanging(global::System.Boolean value);
        partial void OnEsta_disponivelChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblIngrediente", "TblProdutoIngrediente")]
        public EntityCollection<TblProdutoIngrediente> TblProdutoIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblProdutoIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblProdutoIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblProdutoIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblProdutoIngrediente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblPedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblPedido : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblPedido.
        /// </summary>
        /// <param name="pedido_id">Valeur initiale de la propriété Pedido_id.</param>
        /// <param name="dataDoPedido">Valeur initiale de la propriété DataDoPedido.</param>
        public static TblPedido CreateTblPedido(global::System.Int32 pedido_id, global::System.DateTime dataDoPedido)
        {
            TblPedido tblPedido = new TblPedido();
            tblPedido.Pedido_id = pedido_id;
            tblPedido.DataDoPedido = dataDoPedido;
            return tblPedido;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pedido_id
        {
            get
            {
                return _Pedido_id;
            }
            set
            {
                if (_Pedido_id != value)
                {
                    OnPedido_idChanging(value);
                    ReportPropertyChanging("Pedido_id");
                    _Pedido_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Pedido_id");
                    OnPedido_idChanged();
                }
            }
        }
        private global::System.Int32 _Pedido_id;
        partial void OnPedido_idChanging(global::System.Int32 value);
        partial void OnPedido_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataDoPedido
        {
            get
            {
                return _DataDoPedido;
            }
            set
            {
                OnDataDoPedidoChanging(value);
                ReportPropertyChanging("DataDoPedido");
                _DataDoPedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataDoPedido");
                OnDataDoPedidoChanged();
            }
        }
        private global::System.DateTime _DataDoPedido;
        partial void OnDataDoPedidoChanging(global::System.DateTime value);
        partial void OnDataDoPedidoChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblPedido", "TblPedidoItem")]
        public EntityCollection<TblPedidoItem> TblPedidoItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblPedidoItem>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedidoItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblPedidoItem>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedidoItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblPedidoItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblPedidoItem : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblPedidoItem.
        /// </summary>
        /// <param name="pedidoItem_id">Valeur initiale de la propriété PedidoItem_id.</param>
        /// <param name="pedido_id">Valeur initiale de la propriété Pedido_id.</param>
        /// <param name="produto_id">Valeur initiale de la propriété Produto_id.</param>
        public static TblPedidoItem CreateTblPedidoItem(global::System.Int32 pedidoItem_id, global::System.Int32 pedido_id, global::System.Int32 produto_id)
        {
            TblPedidoItem tblPedidoItem = new TblPedidoItem();
            tblPedidoItem.PedidoItem_id = pedidoItem_id;
            tblPedidoItem.Pedido_id = pedido_id;
            tblPedidoItem.Produto_id = produto_id;
            return tblPedidoItem;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PedidoItem_id
        {
            get
            {
                return _PedidoItem_id;
            }
            set
            {
                if (_PedidoItem_id != value)
                {
                    OnPedidoItem_idChanging(value);
                    ReportPropertyChanging("PedidoItem_id");
                    _PedidoItem_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PedidoItem_id");
                    OnPedidoItem_idChanged();
                }
            }
        }
        private global::System.Int32 _PedidoItem_id;
        partial void OnPedidoItem_idChanging(global::System.Int32 value);
        partial void OnPedidoItem_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pedido_id
        {
            get
            {
                return _Pedido_id;
            }
            set
            {
                OnPedido_idChanging(value);
                ReportPropertyChanging("Pedido_id");
                _Pedido_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pedido_id");
                OnPedido_idChanged();
            }
        }
        private global::System.Int32 _Pedido_id;
        partial void OnPedido_idChanging(global::System.Int32 value);
        partial void OnPedido_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Produto_id
        {
            get
            {
                return _Produto_id;
            }
            set
            {
                OnProduto_idChanging(value);
                ReportPropertyChanging("Produto_id");
                _Produto_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Produto_id");
                OnProduto_idChanged();
            }
        }
        private global::System.Int32 _Produto_id;
        partial void OnProduto_idChanging(global::System.Int32 value);
        partial void OnProduto_idChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblPedido", "TblPedido")]
        public TblPedido TblPedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblPedido>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblPedido>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedido").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblPedido> TblPedidoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblPedido>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblPedido>("EServeurDatabaseModel.FK_TblPedidoItem_TblPedido", "TblPedido", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblProduto", "TblProduto")]
        public TblProduto TblProduto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblProduto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblProduto").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblProduto> TblProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblProduto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblProduto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblProduto : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblProduto.
        /// </summary>
        /// <param name="produto_id">Valeur initiale de la propriété Produto_id.</param>
        /// <param name="categoria_id">Valeur initiale de la propriété Categoria_id.</param>
        /// <param name="nome">Valeur initiale de la propriété Nome.</param>
        /// <param name="preco">Valeur initiale de la propriété Preco.</param>
        /// <param name="descricao">Valeur initiale de la propriété Descricao.</param>
        public static TblProduto CreateTblProduto(global::System.Int32 produto_id, global::System.Int32 categoria_id, global::System.String nome, global::System.Decimal preco, global::System.String descricao)
        {
            TblProduto tblProduto = new TblProduto();
            tblProduto.Produto_id = produto_id;
            tblProduto.Categoria_id = categoria_id;
            tblProduto.Nome = nome;
            tblProduto.Preco = preco;
            tblProduto.Descricao = descricao;
            return tblProduto;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Produto_id
        {
            get
            {
                return _Produto_id;
            }
            set
            {
                if (_Produto_id != value)
                {
                    OnProduto_idChanging(value);
                    ReportPropertyChanging("Produto_id");
                    _Produto_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Produto_id");
                    OnProduto_idChanged();
                }
            }
        }
        private global::System.Int32 _Produto_id;
        partial void OnProduto_idChanging(global::System.Int32 value);
        partial void OnProduto_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoria_id
        {
            get
            {
                return _Categoria_id;
            }
            set
            {
                OnCategoria_idChanging(value);
                ReportPropertyChanging("Categoria_id");
                _Categoria_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Categoria_id");
                OnCategoria_idChanged();
            }
        }
        private global::System.Int32 _Categoria_id;
        partial void OnCategoria_idChanging(global::System.Int32 value);
        partial void OnCategoria_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProduto_TblCategoria", "TblCategoria")]
        public TblCategoria TblCategoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblCategoria>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblCategoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblCategoria>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblCategoria").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblCategoria> TblCategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblCategoria>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblCategoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblCategoria>("EServeurDatabaseModel.FK_TblProduto_TblCategoria", "TblCategoria", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblPedidoItem_TblProduto", "TblPedidoItem")]
        public EntityCollection<TblPedidoItem> TblPedidoItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblPedidoItem>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblPedidoItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblPedidoItem>("EServeurDatabaseModel.FK_TblPedidoItem_TblProduto", "TblPedidoItem", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblProduto", "TblProdutoIngrediente")]
        public EntityCollection<TblProdutoIngrediente> TblProdutoIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblProdutoIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProdutoIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblProdutoIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProdutoIngrediente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EServeurDatabaseModel", Name="TblProdutoIngrediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblProdutoIngrediente : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TblProdutoIngrediente.
        /// </summary>
        /// <param name="produtoIngrediente_id">Valeur initiale de la propriété ProdutoIngrediente_id.</param>
        /// <param name="produto_id">Valeur initiale de la propriété Produto_id.</param>
        /// <param name="ingrediente_id">Valeur initiale de la propriété Ingrediente_id.</param>
        public static TblProdutoIngrediente CreateTblProdutoIngrediente(global::System.Int32 produtoIngrediente_id, global::System.Int32 produto_id, global::System.Int32 ingrediente_id)
        {
            TblProdutoIngrediente tblProdutoIngrediente = new TblProdutoIngrediente();
            tblProdutoIngrediente.ProdutoIngrediente_id = produtoIngrediente_id;
            tblProdutoIngrediente.Produto_id = produto_id;
            tblProdutoIngrediente.Ingrediente_id = ingrediente_id;
            return tblProdutoIngrediente;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProdutoIngrediente_id
        {
            get
            {
                return _ProdutoIngrediente_id;
            }
            set
            {
                if (_ProdutoIngrediente_id != value)
                {
                    OnProdutoIngrediente_idChanging(value);
                    ReportPropertyChanging("ProdutoIngrediente_id");
                    _ProdutoIngrediente_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoIngrediente_id");
                    OnProdutoIngrediente_idChanged();
                }
            }
        }
        private global::System.Int32 _ProdutoIngrediente_id;
        partial void OnProdutoIngrediente_idChanging(global::System.Int32 value);
        partial void OnProdutoIngrediente_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Produto_id
        {
            get
            {
                return _Produto_id;
            }
            set
            {
                OnProduto_idChanging(value);
                ReportPropertyChanging("Produto_id");
                _Produto_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Produto_id");
                OnProduto_idChanged();
            }
        }
        private global::System.Int32 _Produto_id;
        partial void OnProduto_idChanging(global::System.Int32 value);
        partial void OnProduto_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ingrediente_id
        {
            get
            {
                return _Ingrediente_id;
            }
            set
            {
                OnIngrediente_idChanging(value);
                ReportPropertyChanging("Ingrediente_id");
                _Ingrediente_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ingrediente_id");
                OnIngrediente_idChanged();
            }
        }
        private global::System.Int32 _Ingrediente_id;
        partial void OnIngrediente_idChanging(global::System.Int32 value);
        partial void OnIngrediente_idChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente")]
        public TblIngrediente TblIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblIngrediente> TblIngredienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblIngrediente>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblIngrediente", "TblIngrediente", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EServeurDatabaseModel", "FK_TblProdutoIngrediente_TblProduto", "TblProduto")]
        public TblProduto TblProduto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProduto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProduto").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblProduto> TblProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblProduto>("EServeurDatabaseModel.FK_TblProdutoIngrediente_TblProduto", "TblProduto", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
